In [1]:
import numpy as np

In [11]:
a = np.linspace(1, 10, 10)
print(a)
print(type(a))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [16]:
b = [a, a, a]
print(b)
print(type(b))

[array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])]
<class 'list'>


In [19]:
c = np.array(b)
print(c)
print(c.shape)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
(3, 10)


In [24]:
print(c.dtype)
print((1-c).dtype)

float64
float64


In [75]:
pos = []

In [78]:
print("pos: {}".format(pos))
for i in range(2):
    pos.append([])


pos: []


In [79]:
print(pos)

[[], []]


In [80]:
pos[0].append([1,1])
print(pos)

[[[1, 1]], []]
