In [1]:
import numpy as np

In [11]:
a = np.linspace(1, 10, 10)
print(a)
print(type(a))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [16]:
b = [a, a, a]
print(b)
print(type(b))

[array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])]
<class 'list'>


In [19]:
c = np.array(b)
print(c)
print(c.shape)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
(3, 10)
